# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.

email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "messages"
      permalink: /:title/

prose:
  rooturl: ''
  media: 'media'
  ignore:
    - _includes
    - _layouts
    - _sass
    - assets
    - .gitignore
    - _config.yml
    - index.html
  metadata:
    _posts:
      - name: "title"
        field: 
          element: "text"
          type: "text"
      - name: "slug"
        field: 
          element: "text"
          label: "Name of Contact"
          help: "enter a short name which matches the _data counterpart"
          type: "text"
      - name: "date"
        field:
          element: "text"
          value: "CURRENT_DATETIME"
          label: "Date"
          help: "automatically added"
          type: "text"
      - name: "members"
        field:
          element: "textarea"
          label: "Members of Groupconversation"
          help: "Format: - SHORT.NAME"
      - name: "conversations"
        field:
          element: "textarea"
          label: "Chat History"
          help: "Format: - dd.mm.yy, hh:mm - USERNAME: MESSAGE"

